### ISSUE TITLE
Browser window doesn't appear when running Behat locally on a Mac

### ISSUE THREAD

**Issue by yhoiseth** [yhoiseth/behat_symfony#1]
## Action
Run `bin/behat`

## Expected result
Chrome browser window appears, showing tests being run.

## Actual result
Tests are running only in the terminal. No browser window appears.

## Packages
I have installed `chromedriver` (2.2.7) and `selenium-server-standalone` (3.0.1) using Homebrew.

**Comment by yhoiseth** [comment]
@htollefsen I tried your example `behat.yml`, and it worked like a charm, with one exception: I don't see the actual browser window. Any idea what I'm missing?

**Comment by htollefsen** [comment]
Can you try marking your feature with `@javascript` or `@js`?

**Comment by yhoiseth** [comment]
@htollefsen Holy fuck! It worked. Thanks!

**Comment by htollefsen** [comment]
You're welcome ;)
